### PR TITLE
Travis CI Integration for Android

### PR DESCRIPTION
**Pull request by amsurana**

### CODE REVIEW

**Comment by jredmondson** [comment]
So, I didn't do the single script automation tests like thing for one reason. If a test succeeds or fails inside of this script, it doesn't produce the green or red text that makes it easy to tell which specific test failed in the Travis CI printout. I'm also not entirely sure it makes sense to make travis-specific environment variables inside of a script file outside of the travis.yml file. Having everything in there seems to make way more sense to me.

Also, I'm not entirely sure that this works with the Travis CI system. If a test fails, are you absolutely certain that it properly accounts for this in the main system?

**Comment by amsurana** [comment]
I have modified the script based on documentation here - 
https://docs.travis-ci.com/user/customizing-the-build/#implementing-complex-build-steps

In `scripts/automation_tests.sh` I have added `set -ev` which prints the line number and command at which the error occurred. 

Please check out the test results for one of the builds - https://travis-ci.org/amsurana/madara/jobs/426721435
[It shows all tests running]

I tried to search for earlier builds, but looks like they are removed from travis build history when I removed old PR. The earlier builds failed at first test case and it printed complete command and line number from the script. That's how I figured out the issue with OSX build and fixed travis script accordingly.

**Comment by jredmondson** [comment]
The first line of that section is "If you have a complex build environment that is hard to configure in the .travis.yml, consider moving the steps into a separate shell script". It's not saying that they recommend the practice. It's just that you might want to do this to simplify configuration into a single script. Were you having trouble with this or something? I actually liked the color coding of the Travis script to help me find specific errors and how many tests were failing.

**Comment by amsurana** [comment]
Okay. When we cross-compile for Android, we cannot run tests on OSX or Ubuntu. So ideally, for Android build to succeed, I had to skip all the test cases from execution.
So moving them to one shell script made sense according to me. The tests are not either run or skipped completely.

**Comment by jredmondson** [comment]
OK, that makes a bit more sense. Let me think about this a bit. The individual tests were as close to a "scoreboard" concept as I could figure out in Travis. This change will cause an all-or-nothing scoreboard where the tests fail or succeed with one color result for all tests (and we're also shortcircuiting all tests on first failure, which may not be very useful in helping to debug the problem).

**Pull request closed without merging**
