### PR TITLE
Commit for feature SW-7381

### PR DESCRIPTION
**Pull request by dfwdeveloper**

### CODE REVIEW

**Comment by dskyle** [comment]
This appears to remove a bunch of code unrelated to the new Cap'n Proto features. Looks like this is clobbering some recent changes to karl. Probably due to not merging properly with current master.

**Comment by jredmondson** [comment]
You need to do a `git merge master` after updating your master in MADARA.

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by dskyle** [comment]
Still clobbering same stuff. Look at changes tab.

**Comment by dskyle** [comment]
Please resolve the conflicts.

**Pull request merged**
