### PR TITLE
Assign thread names to WorkerThreads

### PR DESCRIPTION
**Pull request by samkhal**
This MR makes WorkerThreads assign the first 15 chars of their name to the underlying pthread on linux. This makes it much easier to navigate to a specific thread when debugging, or identify which thread is consuming CPU in a system thread/process viewer like `top`.

### CODE REVIEW

**Comment by jredmondson** [comment]
If we could do a merge with master so Travis CI will kick off integration tests for this, it would be really appreciated!

**Comment by jredmondson** [comment]
This is not working on the Mac build at all. This appears to be a non-POSIX approved way to set this name.

**Comment by jredmondson** [comment]
Can we change this so that it checks that it is not Mac and not Windows, so it will compile correctly on Mac?

**Comment by dskyle** [comment]
Tried to fix OSX issue, but seems to have brought in a bunch of extra stuff that's already in master. Not sure if it's a problem. If so, I'll create a new clean PR.

**Comment by dskyle** [comment]
To avoid merging issues, superseded by: https://github.com/jredmondson/madara/pull/98

**Pull request closed without merging**
